Fix some staticcheck warnings
ffmpeg/dummy.go:36:4: should use stderrBuf.String() instead of string(stderrBuf.Bytes()) (S1030)
id3v2/id3v2_test.go:33:61: should use actual.String() instead of string(actual.Bytes()) (S1030)
leaktest/leaktest.go:217:20: error strings should not be capitalized (ST1005)
writelogger/writelogger_test.go:85:83: should use actualBuf.String() instead of string(actualBuf.Bytes()) (S1030)
ydls/shared_test.go:15:6: func stringsContains is unused (U1000)
ydls/ydls.go:187:3: should use 'return <expr>' instead of 'if <expr> { return <bool> }; return <bool>' (S1008)
ydls/ydls.go:587:4: should write dprc := downloads[ydlFormat.FormatID] instead of dprc, _ := downloads[ydlFormat.FormatID] (S1005)
ydls/ydls.go:611:3: should merge variable declaration with assignment on next line (S1021)